# Generated by Django 6.0.6 on 2026-06-22 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256, null=True)),
                ('Unique_id', models.CharField(max_length=126, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dirdphub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256, null=True)),
                ('Unique_id', models.CharField(max_length=126, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DirOperating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256, null=True)),
                ('Unique_id', models.CharField(max_length=126, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256, null=True)),
                ('Unique_id', models.CharField(max_length=126, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dirdphub_sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256, null=True)),
                ('Unique_id', models.CharField(max_length=126, null=True)),
                ('dir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dphub_sub', to='api.diroperating')),
            ],
        ),
        migrations.CreateModel(
            name='dirCareer_sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256, null=True)),
                ('Unique_id', models.CharField(max_length=126, null=True)),
                ('dir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_sub', to='api.diroperating')),
            ],
        ),
        migrations.CreateModel(
            name='dirOperating_sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256, null=True)),
                ('Unique_id', models.CharField(max_length=126, null=True)),
                ('dir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operating_sub', to='api.diroperating')),
            ],
        ),
        migrations.CreateModel(
            name='Task_tracker_career_sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('Category_carr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_tracker_career_sub', to='api.diroperating_sub')),
            ],
        ),
        migrations.CreateModel(
            name='Task_tracker_career_sub_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_task', models.CharField(max_length=126, null=True)),
                ('Category_carr_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_carr', to='api.diroperating_sub')),
            ],
        ),
        migrations.CreateModel(
            name='Task_tracker_dphub_sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('Category_dp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_tracker_dpub_sub', to='api.diroperating_sub')),
            ],
        ),
        migrations.CreateModel(
            name='Task_tracker_dphub_sub_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_task', models.CharField(max_length=126, null=True)),
                ('Category_dp_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_dp', to='api.diroperating_sub')),
            ],
        ),
        migrations.CreateModel(
            name='Task_tracker_operating_sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('Category_op', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_tracker_dp_operating_sub', to='api.diroperating_sub')),
            ],
        ),
        migrations.CreateModel(
            name='Task_tracker_operating_sub_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_task', models.CharField(max_length=126, null=True)),
                ('Category_op_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_op', to='api.diroperating_sub')),
            ],
        ),
    ]
