# Generated by Django 6.0.6 on 2026-06-22 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Unique_id', models.CharField(max_length=126, null=True)),
                ('dpt', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dirdphub_sub',
            name='dir',
        ),
        migrations.RemoveField(
            model_name='diroperating_sub',
            name='dir',
        ),
        migrations.RemoveField(
            model_name='task_tracker_career_sub',
            name='Category_carr',
        ),
        migrations.RemoveField(
            model_name='task_tracker_operating_sub',
            name='Category_op',
        ),
        migrations.RemoveField(
            model_name='task_tracker_operating_sub_task',
            name='Category_op_task',
        ),
        migrations.RemoveField(
            model_name='task_tracker_dphub_sub_task',
            name='Category_dp_task',
        ),
        migrations.RemoveField(
            model_name='task_tracker_dphub_sub',
            name='Category_dp',
        ),
        migrations.RemoveField(
            model_name='task_tracker_career_sub_task',
            name='Category_carr_task',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(null=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='api.staff')),
            ],
        ),
        migrations.DeleteModel(
            name='dirCareer_sub',
        ),
        migrations.DeleteModel(
            name='dirdphub_sub',
        ),
        migrations.DeleteModel(
            name='Task_tracker_career_sub',
        ),
        migrations.DeleteModel(
            name='Task_tracker_operating_sub',
        ),
        migrations.DeleteModel(
            name='Task_tracker_operating_sub_task',
        ),
        migrations.DeleteModel(
            name='Task_tracker_dphub_sub_task',
        ),
        migrations.DeleteModel(
            name='Task_tracker_dphub_sub',
        ),
        migrations.DeleteModel(
            name='dirOperating_sub',
        ),
        migrations.DeleteModel(
            name='Task_tracker_career_sub_task',
        ),
    ]
