# Generated by Django 6.0.6 on 2026-06-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_staff_remove_dirdphub_sub_dir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
