# Generated by Django 6.0.6 on 2026-06-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_authtoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Main',
            new_name='Admin',
        ),
        migrations.RemoveField(
            model_name='authtoken',
            name='staff',
        ),
        migrations.DeleteModel(
            name='DirCareer',
        ),
        migrations.DeleteModel(
            name='Dirdphub',
        ),
        migrations.DeleteModel(
            name='DirOperating',
        ),
        migrations.AddField(
            model_name='staff',
            name='token',
            field=models.CharField(null=True),
        ),
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
