# Generated by Django 6.0.6 on 2026-06-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_main_admin_remove_authtoken_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(null=True),
        ),
    ]
