# Generated by Django 6.0.6 on 2026-06-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='token',
            field=models.CharField(null=True),
        ),
    ]
