# Generated by Django 6.0.6 on 2026-06-26 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_admin_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('director', 'Director')], default='staff', max_length=20),
        ),
        migrations.CreateModel(
            name='DirectorsTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('status', models.CharField(default='In progress', null=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_tasks', to='api.staff')),
            ],
        ),
    ]
