# Generated by Django 6.0.6 on 2026-06-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_staff_role_directorstask'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(default='staff', max_length=20),
        ),
    ]
