# Generated by Django 6.0.6 on 2026-06-26 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_admin_password_alter_staff_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='Unique_id',
        ),
    ]
