# Generated by Django 6.0.6 on 2026-06-26 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_admin_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='token',
        ),
    ]
