# Generated by Django 6.0.6 on 2026-06-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_admin_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='token',
            field=models.CharField(null=True),
        ),
    ]
