# Generated by Django 6.0.6 on 2026-06-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_admin_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
