# Generated by Django 6.0.6 on 2026-07-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_admin_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='token',
            new_name='auth',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='token',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='Unique_id',
        ),
        migrations.AddField(
            model_name='admin',
            name='auth',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='auth_created_at',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='auth_expire_at',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='refresh',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='refresh_created_at',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='refresh_expire_at',
            field=models.CharField(blank=True, null=True),
        ),
    ]
