# Generated by Django 6.0.6 on 2026-07-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_token_staff_auth_remove_admin_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='auth_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='auth_expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='refresh_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='refresh_expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
