# Generated by Django 6.0.6 on 2026-07-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_staff_auth_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
