# Generated by Django 6.0.6 on 2026-07-24 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_arrival', models.TimeField(null=True)),
                ('date', models.DateField(null=True)),
                ('day', models.CharField(null=True)),
                ('time_of_leave', models.TimeField(null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_arrival', to='api.staff')),
            ],
        ),
    ]
