# Generated by Django 6.0.6 on 2026-09-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_task_description_directorstask_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
