# Generated by Django 6.0.6 on 2026-09-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_staff_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
