# Generated by Django 6.0.6 on 2026-09-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_task_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='number',
        ),
    ]
