# Generated by Django 6.0.6 on 2026-09-16 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_task_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='moved_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves', to='api.task'),
        ),
    ]
