# Generated by Django 6.0.6 on 2026-09-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='settings_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='settings_completed',
            field=models.BooleanField(default=False),
        ),
    ]
