# Generated by Django 6.0.6 on 2026-09-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_admin_settings_completed_staff_settings_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
